language: node_js
node_js:
  - lts/*
cache: npm
script:
  - npm run test
  - npm run predeploy
  - npm run deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: gh-pages
