language: node_js
node_js:
  - lts/*
cache: npm
script:
  - npm run predeploy
  - npm run deploy
deploy:
  provider: pages
  edge: true
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  target-branch: gh-pages
  commit_message: "Deploy release ${TRAVIS_TAG}"
  on:
    branch: master
